# Generated by Django 3.2.7 on 2022-03-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='update_time',
            field=models.DateField(null=True),
        ),
    ]
