# Generated by Django 3.2.7 on 2022-03-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
