# Generated by Django 3.2.7 on 2022-03-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_books_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
