# Generated by Django 3.2.7 on 2022-03-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_books_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='making',
            field=models.BooleanField(default=True),
        ),
    ]
